apiVersion: v1
data:
    github_token: ENC[AES256_GCM,data:afu9pS8DIOiMICrRsUFEnXFrvu2AbA18bW0ZcsyXeARSN0TbjbgGqFocznvS4/7+18f4y0YoQFw=,iv:qD/ecHl9QVH7sAe9OQS/xNPH+klkSaaaFoA7nx1GYE8=,tag:m9BLjObF9wkIt04ns1VvZA==,type:str]
kind: Secret
metadata:
    name: github-arc-token
    namespace: arc-runners
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZGtLYjVYYyt1ZFQ3eHdt
            V1NDTktzSUdrRWNRS1Z4ZjBDM000amFMcXk0CndVQWpJZ2l1cWdxL2xBbyt6MnBB
            VitkVk1CSkIwZDdMTC9CR0FQRzQyM3MKLS0tIC8rQWJ3WDFOME9PbDllYWRzMm9V
            ck9WVTNTb1k5bUNnWmxoMVJsOFludXMKqPvo+7Tmhxr2vCAxJr5WpkZFg8DcFFnW
            JeksH5TCtVoh8GYehP3DC6HTGrvQlGjKeXkErbqotN/i2wZKsH70LA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n4pp5k56sghd7apr3gev9yndf0d8h960wdkv4v8a0nhfzyvw3vgslc8xal
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T14:24:05Z"
    mac: ENC[AES256_GCM,data:H31EW02UHo5d5sO0nmfxrC/LsbHJdkBn5aqzr4lY1K7rxztSQHHD4saWm/FCp3N3SzhkL31W97BX+gZ2McymNc5UpboX1PHHbE8JAL946ajXiFZ9/+Jhy6961cxTiBs+eiVaBe8ZUpjCOf+YunT54ZNHnhfFTHdblCzk9LltdfI=,iv:sXZImkjY6PUtxbZOkj9ZWNUzvw0XW2yzH7C/cg2p/1Y=,tag:Oki5xv8Ees8i2RWf0VLsbw==,type:str]
    version: 3.13.3
